[package]
name = "php-hello"
version = "0.1.0"
description = "Tes sederhana PHP di Wasmer"

[dependencies]
"php/php" = "8.3.400"

[fs]
"/" = "./"

[[command]]
name = "run"
module = "php/php:8.3.400"
runner = "wasi"

[command.annotations.wasi]
main-args = ["hello.php"]
